#ifndef ALERT_MNGR_H
#define ALERT_MNGR_H

#define MOTION_DETECTED (_PULSE_CODE_MINAVAIL + 1)
#define HIGH_CO2 (_PULSE_CODE_MINAVAIL + 2)
#define HIGH_TEMP (_PULSE_CODE_MINAVAIL + 3)
#define DOOR_OPEN (_PULSE_CODE_MINAVAIL + 4)

#endif
